### ISSUE TITLE
move away from mixins

### ISSUE THREAD

**Issue by Haroenv** [firebase/reactfire#100] opened 2016-06-07 12:06 UTC
As listed in [react/docs/reusable-components#no-mixins](https://facebook.github.io/react/docs/reusable-components.html#no-mixins) ES6 react doesn't support mixins anymore. I think it would be interesting to list in the documentation here how to handle this situation.

**Comment by jwngr** [comment] 2016-06-07 17:22
Duplicate of #38.

**Closed by jwngr** 2016-06-07 17:22 UTC
Labels: duplicate

**Comment by Haroenv** [comment] 2016-06-07 17:25
Sorry, didn't see that issue. Thanks anyway :smile:
