### ISSUE TITLE
Any plans to provide a redux adapter?

### ISSUE THREAD

**Issue by lifeinafolder** [firebase/reactfire#115] opened 2016-09-24 04:24 UTC
Hi folks!

Does the team have any plans of providing an adapter that allows firebase to play nicely with redux?

State management in react apps is most popularly driven by redux but I was surprised to find no literature at all on the topic. Atleast it would be beneficial for the community to understand how the core team is thinking about redux-firebase integration?

**Comment by jwngr** [comment] 2016-09-26 03:45
This is sort of a duplicate of https://github.com/firebase/reactfire/issues/114. You should look there for some alternatives. This lib doesn't do anything explicitly to integrate with Redux.

**Closed by jwngr** 2016-09-26 03:45 UTC
